language: swift
osx_image: xcode9.3
script:
  - xcodebuild clean test -project FlatCache.xcodeproj -scheme FlatCache -destination "platform=iOS Simulator,name=iPhone X,OS=11.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
